Geno dev
MaxKolac/zpi pull request #21
Opened 2023-12-02 15:18 UTC by Genocider7

2023-12-02 18:26 UTC, Genocider7 commented
Niechcący zamknąłem sobie, ale z powrotem otworzyłem :v

2023-12-04 07:24 UTC, MaxKolac requested changes

2023-12-04 07:24 UTC, MaxKolac commented on thermalImageParser/communicator.py
> +        save_output_as_file(output, constants.OUPUT_SAVE_FILE)
A to nie jest literówka?

2023-12-04 07:24 UTC, MaxKolac commented on thermalImageParser/constants.template.py
> +OUPUT_SAVE_FILE = 'output.json'
A to nie jest literówka?

2023-12-04 07:42 UTC, Genocider7 commented on thermalImageParser/constants.template.py
> +OUPUT_SAVE_FILE = 'output.json'
Poprawione

2023-12-04 07:50 UTC, MaxKolac approved these changes

2023-12-04 07:50 UTC, merged