Added thermal image converter (doesn't work)
MaxKolac/zpi pull request #26
Opened 2023-12-09 17:14 UTC by Dudi512

2023-12-09 18:38 UTC, MaxKolac commented
Bruh, jeśli nie działa to nie merguj jeszcze.

2023-12-09 18:51 UTC, MaxKolac requested changes

2023-12-09 18:51 UTC, MaxKolac commented on client/src/FormMain.cs
> +        }
Zamiast całej tej metody, spróbuj użyć `Path.Combine(Environment.CurrentDirectory)`.

2023-12-09 18:51 UTC, MaxKolac commented on communicationModels/tempFile.png
Dodawanie plików tymczasowych do kodu źródłowego to słaby pomysł, lepiej to usunąć.

2023-12-09 18:51 UTC, MaxKolac commented on server/src/database.sqlite3
Co dokładnie dodałeś do bazy danych?

2023-12-09 18:55 UTC, Dudi512 commented on server/src/database.sqlite3
Zmieniłem rekordy (adresy ip, typy urządzeń oraz porty) aby client łączył się prawidłowo z bazą. Ilość rekordów nie uległa zmianie.

2023-12-09 18:57 UTC, Dudi512 commented on communicationModels/tempFile.png
Done

2023-12-09 19:11 UTC, Dudi512 commented on client/src/FormMain.cs
> +        }
Samo Path.Combine(Environment.CurrentDirectory) zwraca następującą ścieżkę:
"D:\ZPI\client\src\bin\Debug\net7.0-windows10.0.17763.0"

Zmodyfikowałem funkcję w następujący sposób:

        private string tryGetDirectory()
        {
            string currentDirectory = Environment.CurrentDirectory;
            string communicationModelsPath = Path.Combine(currentDirectory,"..", "..", "..", "..", "..", "communicationModels");
            string fullPath = Path.GetFullPath(communicationModelsPath);

            return fullPath;
        }

Co zwraca ścieżkę "D:\ZPI\communicationModels\", tak samo jak wcześniejsza funkcja.

2023-12-10 13:23 UTC, MaxKolac commented on client/src/FormMain.cs
> +        }
https://github.com/MaxKolac/zpi/pull/26/commits/1e5943da90badb1a03ee4e1f6e8086a1a614ecf4

2023-12-10 13:27 UTC, MaxKolac commented
https://github.com/MaxKolac/zpi/pull/26/commits/1e5943da90badb1a03ee4e1f6e8086a1a614ecf4 
Dwie sprawy:
1. Okazuje się że klasa Image ma kompletnie w poważaniu metadane przy zapisywaniu. Metoda `Image.Save` zapisywała plik, który był faktycznie zdjęciem... ale bez metadanych. Jego rozmiar to był 28 KB, podczas gdy zdjęcia w folderze ExampleImages na ZPICameraSimulator mają po 2 MB. Dlatego Result tego jednego Task'a to był pusty byte[], bo exiftool nie miał co wyciągać z takiego zdjęcia. Trzeba zapisywać to zdjęcie nie klasą Image, a jako surowy ciąg bajtów.
2. Przez przypadek odkryłem też, że jeśli w ścieżce do exiftool.exe jest spacja to wszystko się posypie jeszcze bardziej. Odpalając command prompt z argumentem "/C" trzeba wszystko za tym /C zawrzeć w cudzysłowach, oraz każdą indywidualną ścieżke. Przykład w klasie ImageExtracter.

2023-12-10 13:28 UTC, MaxKolac commented on server/src/database.sqlite3
Nie trzeba edytować bazy danych jaką przy kompilacji serwer kopiuje. Powinieneś te zmiany wprowadzać w bazie danych, która po kompilacji będzie znajdować się w folderze `bin`. W ten sposób nie będziemy sobie nawzajem nadpisywać preferowanych wartości w rekordach.

2023-12-10 13:30 UTC, MaxKolac approved these changes

2023-12-10 13:30 UTC, merged